### ISSUE TITLE
No module named 'vastai_base'

### ISSUE THREAD

**Issue by bluusun** [vast-ai/vast-python#161]
New error - this seemingly worked until recently:

vastai destroy instance $instance_id
Traceback (most recent call last):
  File "/usr/local/bin/vastai", line 5, in <module>
    from vastai.vast import main
  File "/usr/local/lib/python3.10/site-packages/vastai/__init__.py", line 1, in <module>
    from .vastai_sdk import VastAI
  File "/usr/local/lib/python3.10/site-packages/vastai/vastai_sdk.py", line 11, in <module>
    from vastai_base import VastAIBase
ModuleNotFoundError: No module named 'vastai_base'

**Comment by jsbcannell** [comment]
fixed
