### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'create_from'

### ISSUE THREAD

**Issue by vincent-163** [vast-ai/vast-python#87]
When creating an instance I get the error:
```
Traceback (most recent call last):
  File "/home/user/vast.py", line 3523, in <module>
    main()
  File "/home/user/vast.py", line 3509, in main
    sys.exit(args.func(args) or 0)
  File "/home/user/vast.py", line 1144, in create__instance
    "create_from": args.create_from,
AttributeError: 'Namespace' object has no attribute 'create_from'
```

Seems to be related to https://github.com/vast-ai/vast-python/commit/aee96a2a06fc1974faecc5ccfad0ffab952816b6. You might want to search for `create_from` and remove all remaining uses of the argument.

**Comment by jsbcannell** [comment]
fixed
