### ISSUE TITLE
Search offers exception

### ISSUE THREAD

**Issue by ch1ll** [vast-ai/vast-python#91]
```
bash-4.2# vastai search offers 'reliability > 0.98 num_gpus=1 gpu_name=RTX_3090 rented=True'

Traceback (most recent call last):
  File "/usr/local/bin/vastai", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/vastai/vast.py", line 3070, in main
    sys.exit(args.func(args) or 0)
  File "/usr/local/lib/python3.7/site-packages/vastai/vast.py", line 1825, in search__offers
    if row["rented"] is not None:
KeyError: 'rented'
```
This exception occurs with version `0.2.0` and `0.1.8`. Command works fine with `0.1.6`.

**Comment by jsbcannell** [comment]
fixed
